// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chewhecvjmxxszapnxvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZXdoZWN2am14eHN6YXBueHZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NDk5MjgsImV4cCI6MjA3NDQyNTkyOH0.Ck8QoEmP0rJj3NEVt9GXbOE3juN_oPlvHnuXddgoWHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});